"""Regenerate src/emoji_data.h from Wadamesh's baked emoji table.

Usage: python tools/convert_emoji.py <path to wadamesh src/ui-touch/emoji_data.c>

Wadamesh bakes Noto Color Emoji into LVGL image descriptors (16x16,
LV_IMG_CF_TRUE_COLOR_ALPHA: RGB565 little-endian + alpha, 3 bytes/pixel).
We keep the pixels and drop LVGL: a sorted codepoint table plus pixel rows.
"""
import re
import sys

src = open(sys.argv[1], encoding="utf-8").read()
arrs = {m.group(1): [int(x) for x in m.group(2).split(",") if x.strip()]
        for m in re.finditer(r"static const uint8_t e_(\w+)\[\] = \{([^}]*)\};", src)}
dims = {m.group(1): (int(m.group(2)), int(m.group(3)))
        for m in re.finditer(r"static const lv_img_dsc_t d_(\w+) = \{ \{ LV_IMG_CF_TRUE_COLOR_ALPHA, 0, 0, (\d+), (\d+) \}", src)}
table = [(int(m.group(1), 16), m.group(2)) for m in re.finditer(r"\{ 0x([0-9A-Fa-f]+)u, &d_(\w+) \}", src)]

out = sorted((cp, arrs[n]) for cp, n in table if dims[n] == (16, 16) and len(arrs[n]) == 768)
with open("src/emoji_data.h", "w", encoding="ascii") as f:
    f.write("// %d colour emoji, 16x16, RGB565 (little-endian) + 8-bit alpha per pixel.\n" % len(out))
    f.write("// Converted from Wadamesh's baked Noto Color Emoji set (Noto: Apache-2.0 / OFL;\n")
    f.write("// Wadamesh: GPL-3.0). Generated by tools/convert_emoji.py - do not edit.\n#pragma once\n#include <stdint.h>\n\n")
    f.write("static const uint16_t EMOJI_COUNT = %d;\n" % len(out))
    f.write("static const uint32_t EMOJI_CP[EMOJI_COUNT] = {\n" + ",".join("0x%X" % cp for cp, _ in out) + "\n};\n")
    f.write("static const uint8_t EMOJI_PIX[EMOJI_COUNT][768] = {\n")
    for _, a in out:
        f.write("{" + ",".join(map(str, a)) + "},\n")
    f.write("};\n")
print(len(table), "->", len(out))
