// More lock-screen lines. Kept apart from quips.cpp so the list can grow
// without burying the logic. Keep each under ~62 characters so it fits the
// panel, and keep them original.

#pragma once

static const char* const MORE[] = {
  // --- radio life -----------------------------------------------------------
  "Every node is a tiny lighthouse.",
  "Your antenna is doing its best. Be nice to it.",
  "Line of sight is the only real love language.",
  "LoRa: whispering across counties since forever-ish.",
  "Chirp chirp. That's spread spectrum for hello.",
  "Nothing travels farther than a well-placed node.",
  "The noise floor called. It wants its dB back.",
  "SNR positive, mood positive.",
  "A negative SNR is just a packet playing hard to get.",
  "Fresnel zone: the personal space of radio waves.",
  "Somewhere, a packet is bouncing off a grain silo.",
  "Your signal went over a mountain. Show some respect.",
  "Radio waves: invisible, tireless, slightly dramatic.",
  "Coax loss is real. So is heartbreak.",
  "More height, fewer problems.",
  "The best antenna is the one you actually put up.",
  "A roof is just a tower that hasn't met its potential.",
  "It's not range anxiety if the mesh has your back.",
  "Every hop adds a little suspense.",
  "Packets don't need roads. Just friends.",
  "Stay tuned. Literally. 910.525.",
  "Your packet is somewhere between here and hope.",
  "RSSI is how loud. SNR is how clear. Both matter.",
  "Hop limits exist so packets don't wander forever.",
  "Duty cycle: the mesh's way of saying take turns.",
  "Airtime is the mesh's most precious resource.",
  "Short messages travel happier.",
  "Every byte counts at 62.5 kHz.",
  "Spreading factor seven: the sweet spot.",
  "A repeater's job is thankless. Thank one today.",
  "One repeater on a hill beats ten in a basement.",
  "Water absorbs signal. So do trees. So do people.",
  "Your body is a surprisingly good RF blocker.",
  "Hold it higher. No, higher. There you go.",
  "Metal roofs: great for rain, terrible for radio.",
  "Windows are the pager's best friend.",
  "Car roofs make okay ground planes. Just saying.",
  "Coverage maps are hopes drawn in colour.",
  "The mesh gets stronger with every node.",
  "Nodes are like campfires. More is warmer.",
  "Radio silence isn't empty. It's listening.",
  "Somebody's repeater is running on sunshine right now.",
  "Mesh networks: the neighbourhood watch of data.",
  "The internet has towers. We have hills.",
  "Good weather for radio. Bad weather is also fine.",
  "Ionosphere? Never heard of her. We stay local.",
  "Your pager just heard something. Probably.",
  "Listening costs almost nothing. Talking costs airtime.",
  "In the mesh, everyone is infrastructure.",
  "A node on a stick is still a node.",

  // --- the mesh as people ---------------------------------------------------
  "Somebody out there is up late too.",
  "Behind every node is someone who set it up. Wave.",
  "The mesh is just neighbours with antennas.",
  "Say hi on a channel. Someone will say hi back.",
  "Every contact was a stranger once.",
  "A mesh is only as friendly as its users.",
  "Kindness travels the same number of hops.",
  "Your advert just told the valley you exist.",
  "The mesh doesn't know your phone number. Nice.",
  "No algorithm decides who sees your message.",
  "No ads were shown to deliver this message.",
  "Zero data plans were harmed in this conversation.",
  "Owned by nobody. Run by everybody.",
  "This network has no CEO.",
  "Somebody's grandma could be a repeater operator.",
  "Every repeater has a story. Ask about it.",
  "The mesh remembers who showed up.",
  "Be the node you wish to see in the valley.",
  "Plant a node. Watch the mesh grow.",
  "Community-powered, solar-assisted, coffee-fuelled.",
  "Local network, global attitude.",
  "Somewhere a node just rebooted. We don't talk about it.",
  "No one person runs this. That's the point.",
  "You're part of the infrastructure now. Congrats.",
  "Welcome to the least corporate network you'll use.",

  // --- jokes ----------------------------------------------------------------
  "I'd tell you a UDP joke, but you might not get it.",
  "Packets walk into a bar. Some of them.",
  "My favourite band? 915 MHz.",
  "This pager does not do TikTok. You're welcome.",
  "Beep boop. Just kidding, we're way cooler than beeps.",
  "Pagers are back. Tell your friends. Slowly.",
  "Doctors used to carry these. Now you do. Promotion.",
  "No notifications from apps you forgot you installed.",
  "Battery lasts longer when you don't doomscroll.",
  "Can't doomscroll on a pager. Accidental self-care.",
  "The only feed here is the one you have with neighbours.",
  "No likes. No followers. Just messages.",
  "Read receipts are called acks here. Much cooler.",
  "Retry count: a measure of stubbornness.",
  "Flood routing: shouting, but efficient.",
  "Direct path found. The mesh is proud of you.",
  "Path unknown. Adventure mode engaged.",
  "Message sent into the void. The void acked.",
  "Unread messages are just surprises waiting.",
  "Someone typed 'hello?' into a channel. Be the reply.",
  "The keyboard is small. Your thoughts can be too.",
  "Brevity is the soul of LoRa.",
  "Typing on this keyboard builds character.",
  "Thumbs: warmed up. Messages: incoming.",
  "Emoji take two bytes. Worth every one.",
  "A good emoji saves ten words and some airtime.",
  "When in doubt, send a thumbs up.",
  "The scroll wheel is basically a fidget toy with purpose.",
  "Click the wheel. You know you want to.",
  "Rotate responsibly.",
  "This screen is 480 pixels of pure ambition.",
  "Small screen, big mesh.",
  "Built different. Literally, it's a pager.",
  "Your phone is jealous. Don't tell it.",
  "Cell service is optional. Friendship isn't.",
  "No signal? Laughs in LoRa.",
  "The only subscription here is to your neighbours.",
  "Firmware updated. Vibes updated.",
  "Error 404: cell tower not required.",
  "You've got mail. Mesh mail.",
  "Tamagotchi, but it talks to the valley.",
  "Pocket-sized radio station. Keep it pocket-sized.",
  "Ctrl+Z doesn't work on sent packets.",
  "Once flooded, a message cannot be unflooded.",
  "Think before you flood.",
  "The mesh is patient. Your battery is not.",
  "Low battery? The mesh will wait. Mostly.",
  "Charge me like one of your French pagers.",
  "Screen asleep. Radio awake. Always.",
  "Just resting my pixels.",
  "Quietly forwarding your neighbour's hello.",
  "Doing radio things. Please stand by.",
  "Listening intently to the sound of nothing.",
  "Currently hearing: vibes.",
  "If you can read this, the screen works.",
  "Status: dramatically idle.",
  "Lock screen, but make it chatty.",
  "Tap any key. Or don't. I'm not your boss.",
  "Welcome back. The mesh missed you. Slightly.",
  "You again. Good.",
  "Oh hey. Didn't hear you come in.",
  "The pager was here the whole time.",
  "Pro move: checking the mesh before coffee.",
  "Coffee first, then adverts.",
  "Nothing new? That's peaceful.",
  "No news is good news. Still, check the channels.",
  "Quiet mesh, happy mesh.",
  "Busy mesh, happy mesh. It's always happy.",

  // --- outdoors / off-grid --------------------------------------------------
  "Pack water. Pack snacks. Pack the pager.",
  "Trailhead has no bars. You have a mesh.",
  "Hiking tip: tell someone your route. Mesh them.",
  "The mountains are calling. So is the channel.",
  "Camping without cell service? Classic.",
  "Signal loves ridgelines. So do views.",
  "A summit is just a very tall repeater site.",
  "Snow absorbs sound and a bit of signal. Cosy.",
  "Rain fade is mostly a microwave problem. You're fine.",
  "Forest bathing, but make it RF.",
  "Leave no trace. Leave a node, maybe.",
  "The lake is flat. Radio loves flat.",
  "Water carries signal across lakes beautifully.",
  "Canyon walls: great echoes, bad links.",
  "Power outage? The mesh shrugs.",
  "When the grid goes down, the mesh stays up.",
  "Emergencies are why meshes exist. Stay ready.",
  "Know your channels before you need them.",
  "Practice now, so it's easy when it matters.",
  "A charged pager is an emergency plan.",
  "Batteries charged, radios ready, snacks packed.",
  "Storm season is mesh season.",
  "Off grid doesn't mean out of touch.",
  "Wilderness: zero bars, full mesh.",
  "Fire lookout towers would make great repeater sites.",
  "Somewhere a node is covered in snow and still working.",
  "Solar panel, battery, radio: the holy trinity.",
  "Sunny day, full battery. Cloudy day, patience.",
  "Winter nodes need bigger batteries.",
  "Cold weather drains batteries. Keep this pocket-warm.",

  // --- gentle tips ------------------------------------------------------------
  "Tip: channels are group chats. DMs are private.",
  "Tip: rename noisy contacts so you know who's who.",
  "Tip: check Tools for signal and path details.",
  "Tip: a repeater nearby changes everything.",
  "Tip: the map shows nodes that share their position.",
  "Tip: share position only if you're comfortable.",
  "Tip: quick replies save typing on the go.",
  "Tip: turn on quiet hours so nights stay quiet.",
  "Tip: mentions notify you even in busy channels.",
  "Tip: mute a noisy channel instead of leaving it.",
  "Tip: flood adverts are for joining, not every hour.",
  "Tip: Battery saver kicks in at 20% on its own.",
  "Tip: optimised charging holds at 80% overnight.",
  "Tip: charge before a trip, not during the hike.",
  "Tip: an SD card keeps daily backups of your mesh.",
  "Tip: export your contacts before trying new firmware.",
  "Tip: a good channel name makes a friendly channel.",
  "Tip: put your node's location in its name if you like.",
  "Tip: failed DM? Try again after an advert.",
  "Tip: direct paths form after a successful reply.",
  "Tip: the keyboard lights up when a message lands.",
  "Tip: Aurora theme is easiest on the eyes at night.",
  "Tip: lower brightness, longer battery.",
  "Tip: a shorter screen timeout saves a lot of power.",
  "Tip: Wi-Fi only needs to be on for map tiles.",
  "Tip: GPS off saves power if your spot never moves.",
  "Tip: Bluetooth links the pager to the phone app.",
  "Tip: logs in System help when something acts weird.",
  "Tip: trace a route to find the weak hop.",
  "Tip: a repeater's name often hints where it lives.",

  // --- philosophical ----------------------------------------------------------
  "Every message is a small act of trust.",
  "The shortest path isn't always the best one.",
  "Some messages take the scenic route.",
  "Patience is a hop count you can't see.",
  "Connection doesn't need permission.",
  "Distance is just a number of hops.",
  "Small signals, big reach.",
  "What you send ripples outward.",
  "Every node matters. Even the quiet ones.",
  "The mesh is a conversation that never quite ends.",
  "Talk less, say more.",
  "The best messages are the ones worth the airtime.",
  "Signal fades. Friendships don't have to.",
  "A network is just people agreeing to help.",
  "You can't see the mesh, but you can feel it working.",
  "Everything is connected. Some things by LoRa.",
  "Be a good hop in someone's day.",
  "Forward kindness. The mesh does.",
  "Sometimes the ack is the whole conversation.",
  "Not every silence is a failure. Some are sleep.",

  // --- nerdy --------------------------------------------------------------------
  "Chirp spread spectrum: frequency sliding like a trombone.",
  "Ed25519 signed this. Math says it's really them.",
  "Your messages are encrypted. The math is watching.",
  "AES keeps channel chats between channel friends.",
  "Public keys are for sharing. Private keys are for you.",
  "Your identity is 32 bytes. Treat them well.",
  "A packet hash is a fingerprint the mesh remembers.",
  "Duplicate packets get ignored. The mesh has manners.",
  "Coding rate 4/5: a little redundancy goes a long way.",
  "Preamble: the radio clearing its throat.",
  "Sync word: the secret handshake of this mesh.",
  "Bandwidth down, range up. Physics trades fairly.",
  "Doubling the spreading factor roughly doubles airtime.",
  "Every 6 dB of link budget roughly doubles range.",
  "Free space path loss grows with the square of distance.",
  "Ground bounce can help a link or ruin it.",
  "Multipath: when your signal takes several routes.",
  "The ESP32 in here runs two cores and zero ads.",
  "This pager has more RAM than early space missions.",
  "Firmware is just very organised electricity.",
  "Somewhere in here, a PCNT counts your wheel turns.",
  "The fuel gauge counts every milliamp. Politely.",
  "A haptic motor is a tiny spinning weight. Bzzt.",
  "The display is 480 by 222. Every pixel earns its keep.",
  "Wear levelling keeps the flash happy for years.",

  // --- seasonal / time-flavoured ------------------------------------------------
  "Long night? The mesh stays up with you.",
  "Early bird gets the first advert.",
  "Weekend mode: slower replies, longer walks.",
  "Monday? The mesh doesn't know what day it is.",
  "Summer: great for solar nodes. Bad for hot batteries.",
  "Autumn leaves fall. Signal improves slightly. True story.",
  "Winter: fewer leaves, better line of sight.",
  "Spring: trees leaf out, links get a bit harder.",
  "Holiday tip: mesh your family from the cabin.",
  "Road trip? Watch the contacts list grow.",
};
